CREATE TABLE IF NOT EXISTS users (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name VARCHAR(200) NOT NULL,
	email varchar(320)
);

CREATE TABLE IF NOT EXISTS requests(
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	description VARCHAR(1200) NOT NULL,
	user_id BIGINT,
	create_date TIMESTAMP NOT NULL,
		CONSTRAINT fk_requests_to_users FOREIGN KEY(user_id)
		 	REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS items
(
    id 	BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    description VARCHAR(1200),
    available BOOLEAN,
    owner_id BIGINT,
    request_id BIGINT,
    	CONSTRAINT fk_items_to_users FOREIGN KEY(owner_id)
    			 REFERENCES users(id),
    	CONSTRAINT fk_items_to_requests FOREIGN KEY(request_id)
    		REFERENCES requests(id)
);

create type book_state as enum (
	'WAITING',
    'APPROVED',
    'REJECTED',
    'CANCELED' );

CREATE TABLE IF NOT EXISTS bookings
(
	 id	BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	 start_date TIMESTAMP NOT NULL,
	 end_date TIMESTAMP ,
	 item_id BIGINT NOT NULL,
	 booker_id BIGINT NOT NULL,
	 status varchar(10),
	 	CONSTRAINT fk_bookings_to_items FOREIGN KEY(item_id)
    			 REFERENCES items(id),
    	CONSTRAINT fk_bookings_to_users FOREIGN KEY(booker_id)
    		REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS comments
(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	text varchar(4048) NOT NULL,
	item_id BIGINT ,
	author_id BIGINT,
	create_date TIMESTAMP NOT NULL,
		CONSTRAINT fk_comments_to_items FOREIGN KEY(item_id)
    			 REFERENCES items(id),
    	CONSTRAINT fk_comments_to_users FOREIGN KEY(author_id)
    		REFERENCES users(id)
);
